validate Header changes
argoproj-labs/argocd-extension-metrics pull request #38
Opened 2023-03-31 17:45 UTC by schakrad

2023-06-21 19:42 UTC, leoluz requested changes
Please add unit tests validating the new functionality.

2023-07-20 19:36 UTC, schakrad commented
Test cases included in server_test.go

2023-07-20 19:45 UTC, leoluz commented on server/server_test.go
> +	for _, validTest := range validTests {
```suggestion
	for _, validTest := range validTests {
		validTest := validTest
```

2023-07-20 19:46 UTC, leoluz commented on server/server_test.go
> +	for _, invalidTest := range invalidTests {
```suggestion
	for _, invalidTest := range invalidTests {
		invalidTest := invalidTest
```

2023-07-20 19:47 UTC, leoluz commented on server/server_test.go
> +	for _, validTest := range validTests {
```suggestion
	for _, validTest := range validTests {
		validTest := validTest
```

2023-07-20 19:47 UTC, leoluz commented on server/server_test.go
> +	for _, invalidTest := range invalidTests {
```suggestion
	for _, invalidTest := range invalidTests {
		invalidTest := invalidTest
```

2023-07-20 19:59 UTC, schakrad commented on server/server_test.go
> +	for _, validTest := range validTests {
Made the change.

2023-07-20 19:59 UTC, schakrad commented on server/server_test.go
> +	for _, invalidTest := range invalidTests {
Made the change.

2023-07-20 19:59 UTC, schakrad commented on server/server_test.go
> +	for _, invalidTest := range invalidTests {
Made the change.

2023-07-20 20:07 UTC, leoluz approved these changes
LGTM

2023-07-20 20:08 UTC, merged